name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v1
        with:
          just-version: "1.14" # optional semver specification, otherwise latest
      - name: Install pdm
        run: python -m pip install pdm
      - name: Install project
        run: pdm install
      - name: Run tests
        run: just test
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: extractions/setup-just@v1
        with:
          just-version: "1.14" # optional semver specification, otherwise latest
      - name: Install pdm
        run: python -m pip install pdm
      - name: Install project
        run: pdm install
      - name: Run linter
        run: just lint
            
